.TH hex 1 2021-04-24 HeylelOS
.SH NAME
.PP
hex - Hex meta build system Lua interpreter.
.SH SYNOPSIS
.PP
hex [-h] [-C <dir>] rituals...
.SH DESCRIPTION
.PP
Lua interpreter for the Hex meta build system framework.It exports the five hex libraries: fs, env, log, hash and hex and the hex extended lua runtime.However, it doesn't export the whole Lua standard libraries.This was chosen to restrict scripts to the Hex framework paradigm (explicitly avoiding bad programming practices like, for example, using coroutines when they aren't needed).The following components from the Lua standard libraries still are available:
.PP
_G: The base components, which regroups every global functions (like print).
.PP
table: Table related functions.
.PP
string: String related functions.
.PP
utf8: UTF8 related functions
.SH OPTIONS
.PP
-h : Prints usage and exits.
.PP
-C <dir> : Current working directory, changed before doing anything else.
.SH AUTHOR
.PP
Valentin Debon (valentin.debon@heylelos.org)
.SH SEE ALSO
.PP
lua(1).
